In [1]:
import pandas as pd

In [2]:
students = {
    "Name": ["Ram", "Shyam", "Hari", "Ravi"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 92, 76, 88]
}
df = pd.DataFrame(students)
df

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     92
2   Hari   19     76
3   Ravi   22     88

In [6]:
df.loc[2]

Name     Hari
Age        19
Marks      76
Name: 2, dtype: object

In [7]:
df.iloc[2]

Name     Hari
Age        19
Marks      76
Name: 2, dtype: object

In [8]:
df.loc[2,"Marks"]

np.int64(76)

In [12]:
df.iloc[2,1]

np.int64(19)

In [13]:
df

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     92
2   Hari   19     76
3   Ravi   22     88

In [14]:
df.loc[3]

Name     Ravi
Age        22
Marks      88
Name: 3, dtype: object

In [15]:
df.loc[3,"Age"]

np.int64(22)

In [16]:
df.iloc[3,1]

np.int64(22)

In [17]:
df["Marks"]

0    85
1    92
2    76
3    88
Name: Marks, dtype: int64

In [18]:
df.loc[1:3]

    Name  Age  Marks
1  Shyam   21     92
2   Hari   19     76
3   Ravi   22     88

In [19]:
df.iloc[1:3]

    Name  Age  Marks
1  Shyam   21     92
2   Hari   19     76

In [20]:
df

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     92
2   Hari   19     76
3   Ravi   22     88

In [25]:
df.iloc[0:2,0:4:2]

    Name  Marks
0    Ram     85
1  Shyam     92

In [29]:
df.loc[0:1, "Name":"Marks"]

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     92

In [31]:
df.iloc[0:2, 0:2]

    Name  Age
0    Ram   20
1  Shyam   21

In [32]:
df.loc[0:1, "Name":"Age"]

    Name  Age
0    Ram   20
1  Shyam   21

In [33]:
df

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     92
2   Hari   19     76
3   Ravi   22     88

In [34]:
df.loc[0:1, ["Name", "Marks"]]

    Name  Marks
0    Ram     85
1  Shyam     92

In [35]:
df.loc[:, ["Age"]]

   Age
0   20
1   21
2   19
3   22

In [36]:
df

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     92
2   Hari   19     76
3   Ravi   22     88

In [39]:
df.iloc[0:2,0:4:2]

    Name  Marks
0    Ram     85
1  Shyam     92