In [1]:
import pandas as pd

In [2]:
students = {
    "Name": ["sai","hari","ravi","ram"],
    "Age": [20,18,20,23],
    "Marks": [85,85,48,79]
}
df = pd.DataFrame(students)
df

   Name  Age  Marks
0   sai   20     85
1  hari   18     85
2  ravi   20     48
3   ram   23     79

In [4]:
df.shape

(4, 3)

In [5]:
df.size

12

In [6]:
df.ndim

2

In [8]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [10]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
df["Age"]

0    20
1    18
2    20
3    23
Name: Age, dtype: int64

In [13]:
type(df["Age"])

pandas.Series

In [17]:
type(df[["Age"]])

pandas.DataFrame

In [18]:
df[["Age"]]

   Age
0   20
1   18
2   20
3   23

In [19]:
df["Age"]

0    20
1    18
2    20
3    23
Name: Age, dtype: int64

In [21]:
df[["Name","Marks"]]

   Name  Marks
0   sai     85
1  hari     85
2  ravi     48
3   ram     79