In [47]:
import pandas as pd

In [4]:
students = {
    "Name": ["Ram", "Shyam", "Hari", "Ravi"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 92, 76, 88]
}
df = pd.DataFrame(students)
df

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     92
2   Hari   19     76
3   Ravi   22     88

In [7]:
df[df["Marks"]>80]

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     92
3   Ravi   22     88

In [8]:
df[df["Age"]>20]

    Name  Age  Marks
1  Shyam   21     92
3   Ravi   22     88

In [11]:
df[df["Marks"]<90]

   Name  Age  Marks
0   Ram   20     85
2  Hari   19     76
3  Ravi   22     88

In [13]:
df[df["Age"]==21]

    Name  Age  Marks
1  Shyam   21     92

In [14]:
df["Marks"]>80

0     True
1     True
2    False
3     True
Name: Marks, dtype: bool

In [15]:
df["Age"]>20

0    False
1     True
2    False
3     True
Name: Age, dtype: bool

In [18]:
df[(df["Marks"]>80) & (df["Age"]>20)]

    Name  Age  Marks
1  Shyam   21     92
3   Ravi   22     88

In [19]:
df[(df["Marks"]>80)|(df["Age"]==19)]

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     92
2   Hari   19     76
3   Ravi   22     88

In [20]:
df

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     92
2   Hari   19     76
3   Ravi   22     88

In [22]:
df[(df["Marks"]>80) & (df["Age"]<22)]

    Name  Age  Marks
0    Ram   20     85
1  Shyam   21     92

In [26]:
df[(df["Name"]=="Hari") | (df["Age"]==22)]

   Name  Age  Marks
2  Hari   19     76
3  Ravi   22     88

In [28]:
df["Bonus"] = 1000

df

    Name  Age  Marks  Bonus
0    Ram   20     85   1000
1  Shyam   21     92   1000
2   Hari   19     76   1000
3   Ravi   22     88   1000

In [29]:
df["Marks + 5"] = df["Marks"] + 5

df

    Name  Age  Marks  Bonus  Marks + 5
0    Ram   20     85   1000         90
1  Shyam   21     92   1000         97
2   Hari   19     76   1000         81
3   Ravi   22     88   1000         93

In [32]:
df["Adult"] = df["Age"]>=21
df

    Name  Age  Marks  Bonus  Marks + 5  Adult
0    Ram   20     85   1000         90  False
1  Shyam   21     92   1000         97   True
2   Hari   19     76   1000         81  False
3   Ravi   22     88   1000         93   True

In [33]:
df["Marks"] = df["Marks"]+2
df

    Name  Age  Marks  Bonus  Marks + 5  Adult
0    Ram   20     87   1000         90  False
1  Shyam   21     94   1000         97   True
2   Hari   19     78   1000         81  False
3   Ravi   22     90   1000         93   True

In [38]:
df["Age"]+=1
df

    Name  Age  Marks  Bonus  Marks + 5  Adult
0    Ram   24     87   1000         90  False
1  Shyam   25     94   1000         97   True
2   Hari   23     78   1000         81  False
3   Ravi   26     90   1000         93   True

In [39]:
df["Marks"]-=2

In [40]:
df

    Name  Age  Marks  Bonus  Marks + 5  Adult
0    Ram   24     85   1000         90  False
1  Shyam   25     92   1000         97   True
2   Hari   23     76   1000         81  False
3   Ravi   26     88   1000         93   True

In [41]:
df["Bonus"]+=500
df

    Name  Age  Marks  Bonus  Marks + 5  Adult
0    Ram   24     85   1500         90  False
1  Shyam   25     92   1500         97   True
2   Hari   23     76   1500         81  False
3   Ravi   26     88   1500         93   True

In [51]:
new_df = df.drop(columns=["Bonus"])
new_df

    Name  Age  Marks  Marks + 5  Adult
0    Ram   24     85         90  False
1  Shyam   25     92         97   True
2   Hari   23     76         81  False
3   Ravi   26     88         93   True

In [57]:
df

    Name  Age  Marks  Marks + 5  Adult
0    Ram   24     85         90  False
1  Shyam   25     92         97   True
2   Hari   23     76         81  False
3   Ravi   26     88         93   True

In [58]:
temp = df.drop(columns=["Adult"])
temp

    Name  Age  Marks  Marks + 5
0    Ram   24     85         90
1  Shyam   25     92         97
2   Hari   23     76         81
3   Ravi   26     88         93

In [59]:
df

    Name  Age  Marks  Marks + 5  Adult
0    Ram   24     85         90  False
1  Shyam   25     92         97   True
2   Hari   23     76         81  False
3   Ravi   26     88         93   True

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      str
 1   Age        4 non-null      int64
 2   Marks      4 non-null      int64
 3   Marks + 5  4 non-null      int64
 4   Adult      4 non-null      bool
dtypes: bool(1), int64(3), str(1)
memory usage: 264.0 bytes

In [61]:
df.describe()

             Age      Marks  Marks + 5
count   4.000000   4.000000   4.000000
mean   24.500000  85.250000  90.250000
std     1.290994   6.800735   6.800735
min    23.000000  76.000000  81.000000
25%    23.750000  82.750000  87.750000
50%    24.500000  86.500000  91.500000
75%    25.250000  89.000000  94.000000
max    26.000000  92.000000  97.000000

In [62]:
df

    Name  Age  Marks  Marks + 5  Adult
0    Ram   24     85         90  False
1  Shyam   25     92         97   True
2   Hari   23     76         81  False
3   Ravi   26     88         93   True

In [63]:
df["Grade"] = ["A", "A", "B", "A"]

df

    Name  Age  Marks  Marks + 5  Adult Grade
0    Ram   24     85         90  False     A
1  Shyam   25     92         97   True     A
2   Hari   23     76         81  False     B
3   Ravi   26     88         93   True     A

In [64]:
df["Grade"].value_counts()

Grade
A    3
B    1
Name: count, dtype: int64

In [65]:
df.sort_values("Marks")

    Name  Age  Marks  Marks + 5  Adult Grade
2   Hari   23     76         81  False     B
0    Ram   24     85         90  False     A
3   Ravi   26     88         93   True     A
1  Shyam   25     92         97   True     A

In [66]:
df.sort_values("Marks", ascending=False)

    Name  Age  Marks  Marks + 5  Adult Grade
1  Shyam   25     92         97   True     A
3   Ravi   26     88         93   True     A
0    Ram   24     85         90  False     A
2   Hari   23     76         81  False     B

In [67]:
df

    Name  Age  Marks  Marks + 5  Adult Grade
0    Ram   24     85         90  False     A
1  Shyam   25     92         97   True     A
2   Hari   23     76         81  False     B
3   Ravi   26     88         93   True     A

In [68]:
df.head(3)

    Name  Age  Marks  Marks + 5  Adult Grade
0    Ram   24     85         90  False     A
1  Shyam   25     92         97   True     A
2   Hari   23     76         81  False     B

In [69]:
df.tail(1)

   Name  Age  Marks  Marks + 5  Adult Grade
3  Ravi   26     88         93   True     A

In [72]:
df.sort_values("Age", ascending=False)

    Name  Age  Marks  Marks + 5  Adult Grade
3   Ravi   26     88         93   True     A
1  Shyam   25     92         97   True     A
0    Ram   24     85         90  False     A
2   Hari   23     76         81  False     B

In [73]:
df.value_counts("Grade")

Grade
A    3
B    1
Name: count, dtype: int64